-- Run this in the Supabase SQL Editor after phase3_setup.sql

-- 1. Allow anyone to read scan_reports (needed for the community map)
DROP POLICY IF EXISTS "allow_select_for_anon" ON public.scan_reports;
CREATE POLICY "allow_select_for_anon"
ON public.scan_reports FOR SELECT
TO anon, authenticated
USING (true);

-- 2. Devices table for proximity push notifications
CREATE TABLE IF NOT EXISTS public.devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  push_token TEXT NOT NULL UNIQUE,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  geom GEOGRAPHY(POINT, 4326) GENERATED ALWAYS AS (
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
  ) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.devices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_insert_devices" ON public.devices;
CREATE POLICY "allow_insert_devices"
ON public.devices FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "allow_select_devices" ON public.devices;
CREATE POLICY "allow_select_devices"
ON public.devices FOR SELECT
TO anon, authenticated
USING (true);

-- Update (upsert) policy
DROP POLICY IF EXISTS "allow_update_devices" ON public.devices;
CREATE POLICY "allow_update_devices"
ON public.devices FOR UPDATE
TO anon, authenticated
USING (true);

-- 3. PostGIS helper: find devices within a radius of a scan
CREATE OR REPLACE FUNCTION public.get_devices_near(
  scan_lat DOUBLE PRECISION,
  scan_lng DOUBLE PRECISION,
  radius_m DOUBLE PRECISION DEFAULT 50000
)
RETURNS TABLE(push_token TEXT, distance_m DOUBLE PRECISION)
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT
    push_token,
    ST_Distance(
      geom,
      ST_SetSRID(ST_MakePoint(scan_lng, scan_lat), 4326)::geography
    ) AS distance_m
  FROM public.devices
  WHERE ST_DWithin(
    geom,
    ST_SetSRID(ST_MakePoint(scan_lng, scan_lat), 4326)::geography,
    radius_m
  );
$$;

-- 4. Seed demo scan_reports near LA (34.0522, -118.2437) for the community map
INSERT INTO public.scan_reports (disease_id, timestamp, latitude, longitude, user_text, is_synced)
VALUES
  ('leaf_rust',     NOW() - INTERVAL '2 hours',   34.0632, -118.2307, 'Upper canopy with orange pustules after humid morning', true),
  ('blight',        NOW() - INTERVAL '5 hours',   34.0412, -118.2567, 'Dark concentric lesions near drip line on tomatoes',   true),
  ('leaf_rust',     NOW() - INTERVAL '1 day',     34.0751, -118.2191, 'Wheat field east corner showing rust spread',          true),
  ('stripe_rust',   NOW() - INTERVAL '3 hours',   34.0488, -118.2732, 'Yellow stripe pattern on flag leaf',                   true),
  ('late_blight',   NOW() - INTERVAL '6 hours',   34.0563, -118.2613, 'Water-soaked lesions on potato lower leaves',          true),
  ('healthy',       NOW() - INTERVAL '30 minutes',34.0601, -118.2451, 'Routine check — all clear this row',                   true),
  ('leaf_rust',     NOW() - INTERVAL '8 hours',   34.0710, -118.2580, 'Same rust showing on neighboring field',               true),
  ('powdery_mildew_wheat', NOW() - INTERVAL '12 hours', 34.0350, -118.2200, 'White powdery coating on wheat top leaves',      true)
ON CONFLICT DO NOTHING;
